AWSTemplateFormatVersion: '2010-09-09'

Description: Create an S3 Bucket from a specified parameter

Parameters:
  S3BucketName:
    Description: The name of the S3 bucket to create
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName

Outputs:
  S3BucketArn:
    Description: S3 Bucket ARN
    Value: !GetAtt S3Bucket.Arn
